stages:
  - gitlab
  - docker

build-job:
  stage: gitlab
  script:
    - echo "Pull changes from GitLab"
    - git status
    - git stash
    - git pull origin main
    - echo "GIT work"
    - cp /var/espace-prive/espace-prive-api/.env .env
  only: 
    - main
  
docker-job:
  stage: docker
  script:
    - echo "Docker stage"
    # Check if the container exists before attempting to remove it
    - docker rm -f private-access-api || echo "no container named private-access-api"
    # Check if the image exists before attempting to remove it
    - docker rmi private-access-api || echo "no images  named private-access-api"
    - docker build -t private-access-api ./
    - docker run --name private-access-api -p 5651:4000 --network bridge -d private-access-api
    - docker ps
  only:
    - main
